# Generated by Django 3.2.7 on 2021-10-02 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Servicio',
        ),
    ]
